version: '2'
services: 
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpw

  node: 
    build: .
    ports:
      - "8080:8080"
    links:
      - postgres
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpw
