version: '2'
services: 
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file: ./config.env

  app: 
    build: app/.
    ports:
      - "8080:8080"
    links:
      - postgres
    env_file: ./config.env
